### ISSUE TITLE
glmnetMex much slower on linux than windows?

### ISSUE THREAD

**Issue by justjul** [jasonnicholson/glmnet_matlab#2]
Hi,
I'm trying to scale up my code by running glmnet on a linux cluster (with Matlab 2021a). Unfortunately, the mex file is much slower than on my windows PC (up to 30 times for my particular application), even after re-compiling. I was wondering if you had encountered similar issues or had advices on where to look for a workaround solution (didn't get any reply from the original glmnet developpers). 
Best,
Julien

**Comment by jasonnicholson** [comment]
The first thought I have is related to the Intel compiler. The Intel compiler is faster than GCC, as shown below. My windows version uses the Intel compiler. Try the Intel FORTRAN compiler on Linux if you can.
![image](https://user-images.githubusercontent.com/1058191/164550459-20535a07-1553-498c-ac2b-fc3302bbd23c.png)

However, you're talking about 30x. Intel vs. GCC should not be explained by 30x. Are we talking about 0.1 seconds vs. 3.0 seconds? If we are, I don't think the compiler is the problem. 

If you have access to a cluster implying you have resources, is there a good reason to use glmnet over Mathwork's Statistics and Machine learning toolbox? Could you use the [Lasso tools](https://www.mathworks.com/help/stats/lasso.html?searchHighlight=lasso&s_tid=srchtitle_lasso_1) in MATLAB's [Statistics and Machine Learning Toolbox](https://www.mathworks.com/help/stats/index.html?s_tid=CRUX_lftnav)? This, combined with Mathworks parallel tools, should get you a massive speedup. This version of glmnet is really for those without resources and are just trying to get by.

**Comment by jasonnicholson** [comment]
I am going to close this issue. Reply and reopen if you want further correspondance.
